/*
    * SEQUENCE
*/
-- * 시퀀스 생성, SEQ_TEST
CREATE SEQUENCE SEQ_TEST;

-- * 시퀀스 조회
SELECT * FROM USER_SEQUENCES;

-- SEQ_EMPNO
-- 시작번호 : 300, 증가 값 : 5, 최대 값 : 310, NOCYCLE, NOCACHE
CREATE SEQUENCE SEQ_EMPNO START WITH 300 INCREMENT BY 5 MAXVALUE 310 NOCACHE;

SELECT * FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_EMPNO';

/*
    * 시퀀스 사용 
*/

-- SEQ_EMPNO 시퀀스의 현재 시퀀스 값 조회 
SELECT SEQ_EMPNO.CURRVAL FROM DUAL;

SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;

SELECT SEQ_EMPNO.CURRVAL FROM DUAL;

SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;

SELECT * FROM USER_SEQUENCES;

SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- 최대 값을 넘어가는 경우 오류 발생


/*
    * 시퀀스 변경 
*/
-- SEQ_EMPNO 시퀀스의 증가값을 10, 최대값을 400으로 변경
ALTER SEQUENCE SEQ_EMPNO MAXVALUE 400 INCREMENT BY 10;

SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;



/*
    * 시퀀스 삭제
*/

DROP SEQUENCE SEQ_EMPNO;

--------------------------------------------------------------------------------

/*
    * EMPLOYEE 테이블에 시퀀스 사용
    사번 컬럼에 사용 (EMP_ID)
*/
-- * 시퀀스 생성 (SEQ_EID), START WITH 300, NOCACHE, INCREMENT BY 1
CREATE SEQUENCE SEQ_EID START WITH 300 NOCACHE INCREMENT BY 1;

-- * 시퀀스 사용, EMPLOYEE 테이블에 테이터 추가
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, JOB_CODE, HIRE_DATE) 
    VALUES (SEQ_EID.NEXTVAL, '박영철', '000000-1000000', 'J5', SYSDATE);
    
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, JOB_CODE, HIRE_DATE) 
    VALUES (SEQ_EID.NEXTVAL, '박영철', '000000-1000000', 'J5', SYSDATE);
    
SELECT * FROM EMPLOYEE;

ROLLBACK;














