-- 실습용 계정
-- 계정명 : C##WORKBOOK / 비밀번호 : WORKBOOK

-- 계정 생성
CREATE USER C##WORKBOOK IDENTIFIED BY WORKBOOK;

-- 최소 권한 부여 
GRANT CONNECT, RESOURCE TO C##WORKBOOK;

-- 테이블 스페이스 관련 설정 
ALTER USER C##WORKBOOK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;