-- [Basic SELECT]

-- 1. 대학교 학과 이름, 계열 표시. 단, 출력 헤더는 "학과 명", "계열"으로 표시
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열" FROM TB_DEPARTMENT;

-- 2. 학과 정원 출력, CAPACITY
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명' || ' 입니다.' "학과별 정원" FROM TB_DEPARTMENT;

-- 3. "국어국문학과" 여학생 중 휴학생 조회. 학과 테이블 '학과 코드' 조회 
-- DEPARTMENT_NO = 001
-- ABSENCE_YN 
SELECT STUDENT_NAME FROM TB_STUDENT WHERE ABSENCE_YN = 'Y' AND DEPARTMENT_NO = '001';

-- 4. 대출 도서 장기 연체자 이름 게시. 학번 조회
-- A513079, A513090, A513091, A513110, A513119
SELECT STUDENT_NAME FROM TB_STUDENT WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 5. 입학 정원이 20 ~ 30명 학과 학과 이름과 계열 출력
SELECT DEPARTMENT_NAME, CATEGORY FROM TB_DEPARTMENT WHERE CAPACITY BETWEEN 20 AND 30;

-- 6. 총장 이름 출력. 총장은 소속 학과가 없다. 
SELECT PROFESSOR_NAME FROM TB_PROFESSOR WHERE DEPARTMENT_NO IS NULL;

-- 7. 학과가 지정되어 있지 않은 학생 조회 
SELECT STUDENT_NAME FROM TB_STUDENT WHERE DEPARTMENT_NO IS NULL;

-- 8. 선수 과목 존재 과목의 과목 번호 조회. 선수 과목 여부 확인
SELECT CLASS_NO FROM TB_CLASS WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 대학 계열 조회
SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT;

-- 10. 02 학번 전주 거주자 중 휴학생 제외 학생 학번, 이름, 주민번호 출력 
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT 
WHERE 
ABSENCE_YN = 'N' 
AND INSTR(STUDENT_ADDRESS, '전주시') > 0
AND TO_CHAR(ENTRANCE_DATE, 'YY') = '02';



